Debug sonarqube

diff --git a/.cloudbees/workflows/my-workflow.yaml b/.cloudbees/workflows/my-workflow.yaml
--- a/.cloudbees/workflows/my-workflow.yaml
+++ b/.cloudbees/workflows/my-workflow.yaml
@@ -135,6 +135,7 @@ jobs:
           curl -u ${{ secrets.SONAR_USER }}:${{ secrets.SONAR_TOKEN }} \
           "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=HackersOrganized&severities=BLOCKER,CRITICAL,MAJOR,MINOR" \
           -o sonar-issues.json
+          cat sonar-issues.json
           BLOCKER_COUNT=$(jq '[.issues[] | select(.severity=="BLOCKER")] | length' sonar-issues.json)
           CRITICAL_COUNT=$(jq '[.issues[] | select(.severity=="CRITICAL")] | length' sonar-issues.json)
           MAJOR_COUNT=$(jq '[.issues[] | select(.severity=="MAJOR")] | length' sonar-issues.json)
@@ -161,6 +162,13 @@ jobs:
 ## SPIKE-BUSTER to enter a CBC interogtation step here. 
     environment: DOW Production
     steps:
+      - name: Quality gate
+        if: ${{ jobs.scan.outputs.CRITICAL_COUNT > 1 }} 
+        uses: docker://alpine:3.18
+        run: |
+          echo "Deployment gate failed: Critical test failure"
+          exit 1
+
       - name: Checkout
         uses: cloudbees-io/checkout@v1
       - uses: cashokannamalai/kubeconfig@v1
